name: bioyoda
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - adwaita-icon-theme=49.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alsa-lib=1.2.15.1
  - amply=0.1.6
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argparse-dataclass=2.0.0
  - async-timeout=5.0.1
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - backports.zstd=1.2.0
  - beautifulsoup4=4.14.3
  - biopython=1.86
  - blas=2.305
  - blas-devel=3.11.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - conda-inject=1.3.2
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - contourpy=1.3.3
  - cpuonly=2.0
  - cpython=3.12.12
  - cramjam=2.11.0
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-version=12.9
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - diamond=2.1.14
  - dill=0.3.7
  - dnspython=2.8.0
  - docutils=0.22.4
  - dpath=2.2.0
  - eido=0.2.4
  - email-validator=2.3.0
  - email_validator=2.3.0
  - epoxy=1.5.10
  - exceptiongroup=1.3.1
  - faiss-cpu=1.13.2
  - fastapi=0.127.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.127.0
  - fastparquet=2025.12.0
  - ffmpeg=8.0.1
  - filelock=3.20.1
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - gdk-pixbuf=2.44.4
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib-tools=2.86.3
  - glog=0.7.1
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.3.0
  - grpcio=1.73.1
  - gtk3=3.24.43
  - gts=0.7.6
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hf-xet=1.2.1
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - huggingface_hub=0.36.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - immutables=0.21
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - jinja2=3.1.6
  - joblib=1.5.3
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_core=5.9.1
  - kaldi=5.5.1172
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.26.3
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcufft=11.4.1.4
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libde265=1.0.15
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libfaiss=1.13.2
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libmagma_sparse=2.9.0
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.9.86
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.3.0
  - libopenvino-auto-batch-plugin=2025.3.0
  - libopenvino-auto-plugin=2025.3.0
  - libopenvino-hetero-plugin=2025.3.0
  - libopenvino-intel-cpu-plugin=2025.3.0
  - libopenvino-intel-gpu-plugin=2025.3.0
  - libopenvino-intel-npu-plugin=2025.3.0
  - libopenvino-ir-frontend=2025.3.0
  - libopenvino-onnx-frontend=2025.3.0
  - libopenvino-paddle-frontend=2025.3.0
  - libopenvino-pytorch-frontend=2025.3.0
  - libopenvino-tensorflow-frontend=2025.3.0
  - libopenvino-tensorflow-lite-frontend=2025.3.0
  - libopus=1.6
  - libparquet=22.0.0
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=18.1
  - libprotobuf=6.31.1
  - librdkit=2025.09.3
  - libre2-11=2025.11.05
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libutf8proc=2.11.2
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - logmuse=0.2.8
  - lxml=6.0.2
  - lz4-c=1.10.0
  - magma=2.9.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - nbformat=5.10.4
  - ncurses=6.5
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - nomkl=3.0
  - numpy=2.4.0
  - ocl-icd=2.3.3
  - openblas=0.3.30
  - opencl-headers=2025.06.13
  - openfst=1.8.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - optree=0.18.0
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - pcre2=10.47
  - pephubclient=0.4.4
  - peppy=0.40.8
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - portalocker=2.10.1
  - postgresql=18.1
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - psutil=7.2.0
  - psycopg2=2.9.10
  - psycopg2-binary=2.9.10
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulp=2.8.0
  - pulseaudio-client=17.0
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pycairo=1.29.0
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.10.6
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyparsing=3.3.1
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.12
  - python-multipart=0.0.21
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.12
  - pytorch=2.9.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - qdrant-client=1.16.2
  - qhull=2020.2
  - rav1e=0.7.1
  - rdkit=2025.09.3
  - re2=2025.11.05
  - readline=8.3
  - redis-py=7.1.0
  - referencing=0.37.0
  - regex=2025.11.3
  - reportlab=4.4.7
  - requests=2.32.5
  - reretry=0.11.8
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - rlpycairo=0.4.0
  - rpds-py=0.30.0
  - ruamel.yaml=0.18.17
  - ruamel.yaml.clib=0.2.15
  - s2n=1.6.2
  - safetensors=0.7.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - sdl2=2.32.56
  - sdl3=3.2.28
  - sentence-transformers=5.2.0
  - setuptools=80.9.0
  - shaderc=2025.5
  - shellingham=1.5.4
  - six=1.17.0
  - slack-sdk=3.39.0
  - slack_sdk=3.39.0
  - sleef=3.9.0
  - smart_open=7.5.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - spirv-tools=2025.4
  - sqlalchemy=2.0.45
  - starlette=0.50.0
  - structlog=25.5.0
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - throttler=1.2.2
  - tk=8.6.13
  - tokenizers=0.22.2
  - tomli=2.3.0
  - torchaudio=2.9.1
  - torchcodec=0.8.1
  - torchvision=0.24.1
  - torchvision-extra-decoders=0.0.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.57.3
  - typer=0.20.1
  - typer-slim=0.20.1
  - typer-slim-standard=0.20.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzcode=2025c
  - tzdata=2025c
  - ubiquerg=0.8.0
  - unicodedata2=17.0.0
  - urllib3=2.6.2
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - veracitools=0.1.3
  - watchfiles=1.1.1
  - wayland=1.24.0
  - wayland-protocols=1.47
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.3
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2025.1
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - yte=1.9.4
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - accelerate==1.14.0
      - airium==0.2.7
      - alabaster==1.0.0
      - anthropic==0.75.0
      - antlr4-python3-runtime==4.9.3
      - arrow==1.4.0
      - asttokens==3.0.1
      - babel==2.18.0
      - bcp47==0.1.0
      - blosc2==4.5.1
      - cachetools==6.2.4
      - cattrs==26.1.0
      - cbor==1.0.0
      - cffi==2.0.0
      - cfgraph==0.2.1
      - chanfig==0.0.116
      - chardet==5.2.0
      - class-resolver==0.7.1
      - cryptography==49.0.0
      - curies==0.13.13
      - danling==0.4.2
      - datasets==4.4.2
      - decorator==5.3.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - deprecation==2.1.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - duckdb==1.5.4
      - et-xmlfile==2.0.0
      - eutils==0.6.1
      - executing==2.2.1
      - fair-esm==2.0.0
      - fastobo==0.14.1
      - fpsim2==0.7.4
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - funowl==0.2.3
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.45.0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - graphviz==0.21
      - grpcio-status==1.71.2
      - grpcio-tools==1.71.2
      - hbreader==0.9.1
      - httplib2==0.31.0
      - httpx-sse==0.4.3
      - ijson==3.5.0
      - imagesize==2.0.0
      - inscriptis==2.7.1
      - ipython==9.14.1
      - ipython-pygments-lexers==1.1.1
      - ir-datasets==0.5.11
      - isodate==0.7.2
      - isoduration==20.11.0
      - jedi==0.20.0
      - jinjanator==25.3.1
      - jinjanator-plugins==25.1.0
      - jiter==0.12.0
      - json-flattener==0.1.9
      - jsonasobj==1.3.1
      - jsonasobj2==1.0.4
      - jsonlines==4.0.0
      - jsonpickle==4.1.2
      - jsonpointer==3.1.1
      - kgcl-rdflib==0.5.0
      - kgcl-schema==0.6.9
      - lark==1.3.1
      - lazy-imports==1.2.0
      - lightning-utilities==0.15.3
      - linkify-it-py==2.1.0
      - linkml==1.11.1
      - linkml-renderer==0.3.1
      - linkml-runtime==1.11.1
      - lz4==4.4.5
      - matplotlib-inline==0.2.2
      - mcp==1.28.0
      - mdit-py-plugins==0.6.1
      - more-click==0.1.3
      - msgpack==1.2.1
      - multimolecule==0.0.5
      - ndex2==3.11.0
      - ndindex==1.10.1
      - numexpr==2.14.1
      - oaklib==0.6.23
      - ols-client==0.2.1
      - ontoportal-client==0.0.9
      - openai==2.14.0
      - openpyxl==3.1.5
      - parse==1.22.1
      - parso==0.8.7
      - pexpect==4.9.0
      - plotext==5.3.2
      - prefixcommons==0.1.12
      - prefixmaps==0.2.6
      - prompt-toolkit==3.0.52
      - pronto==2.7.3
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pyjsg==0.12.4
      - pyjwt==2.13.0
      - pyshex==0.8.1
      - pyshexc==0.9.1
      - pysolr==3.11.0
      - pystow==0.8.17
      - pytest-logging==2015.11.4
      - pyvis==0.3.2
      - rank-bm25==0.2.2
      - ratelimit==2.2.1
      - rdflib==7.6.0
      - rdflib-jsonld==0.6.1
      - rdflib-shim==1.0.3
      - requests-cache==1.3.2
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - roman-numerals==4.1.0
      - rsa==4.9.1
      - semsql==0.4.0
      - sentencepiece==0.2.1
      - shexjsg==0.9.0
      - snowballstemmer==3.1.1
      - sparqlslurper==0.5.1
      - sparqlwrapper==2.0.0
      - sphinx==9.1.0
      - sphinx-click==6.2.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy-utils==0.38.3
      - sse-starlette==3.4.5
      - sssom==0.4.21
      - sssom-schema==1.1.0a5
      - stack-data==0.6.3
      - tables==3.11.1
      - tenacity==9.1.4
      - textual==8.2.7
      - textual-plotext==1.0.1
      - tiktoken==0.12.0
      - torchdata==0.11.0
      - torchmetrics==1.9.0
      - trec-car-tools==2.6
      - uc-micro-py==2.0.0
      - unlzw3==0.2.3
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - url-normalize==3.0.0
      - validators==0.35.0
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - watchdog==6.0.0
      - wcwidth==0.8.1
      - webcolors==25.10.0
      - zlib-state==0.1.12
