# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import app_pb2 as app__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BiobtreeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/pbuf.BiobtreeService/Search',
                request_serializer=app__pb2.SearchRequest.SerializeToString,
                response_deserializer=app__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Mapping = channel.unary_unary(
                '/pbuf.BiobtreeService/Mapping',
                request_serializer=app__pb2.MappingRequest.SerializeToString,
                response_deserializer=app__pb2.MappingResponse.FromString,
                _registered_method=True)
        self.Entry = channel.unary_unary(
                '/pbuf.BiobtreeService/Entry',
                request_serializer=app__pb2.EntryRequest.SerializeToString,
                response_deserializer=app__pb2.EntryResponse.FromString,
                _registered_method=True)
        self.Page = channel.unary_unary(
                '/pbuf.BiobtreeService/Page',
                request_serializer=app__pb2.PageRequest.SerializeToString,
                response_deserializer=app__pb2.PageResponse.FromString,
                _registered_method=True)
        self.Filter = channel.unary_unary(
                '/pbuf.BiobtreeService/Filter',
                request_serializer=app__pb2.FilterRequest.SerializeToString,
                response_deserializer=app__pb2.FilterResponse.FromString,
                _registered_method=True)
        self.Meta = channel.unary_unary(
                '/pbuf.BiobtreeService/Meta',
                request_serializer=app__pb2.MetaRequest.SerializeToString,
                response_deserializer=app__pb2.MetaResponse.FromString,
                _registered_method=True)
        self.ListGenomes = channel.unary_unary(
                '/pbuf.BiobtreeService/ListGenomes',
                request_serializer=app__pb2.ListGenomesRequest.SerializeToString,
                response_deserializer=app__pb2.ListGenomesResponse.FromString,
                _registered_method=True)


class BiobtreeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Entry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Page(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Filter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Meta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGenomes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiobtreeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=app__pb2.SearchRequest.FromString,
                    response_serializer=app__pb2.SearchResponse.SerializeToString,
            ),
            'Mapping': grpc.unary_unary_rpc_method_handler(
                    servicer.Mapping,
                    request_deserializer=app__pb2.MappingRequest.FromString,
                    response_serializer=app__pb2.MappingResponse.SerializeToString,
            ),
            'Entry': grpc.unary_unary_rpc_method_handler(
                    servicer.Entry,
                    request_deserializer=app__pb2.EntryRequest.FromString,
                    response_serializer=app__pb2.EntryResponse.SerializeToString,
            ),
            'Page': grpc.unary_unary_rpc_method_handler(
                    servicer.Page,
                    request_deserializer=app__pb2.PageRequest.FromString,
                    response_serializer=app__pb2.PageResponse.SerializeToString,
            ),
            'Filter': grpc.unary_unary_rpc_method_handler(
                    servicer.Filter,
                    request_deserializer=app__pb2.FilterRequest.FromString,
                    response_serializer=app__pb2.FilterResponse.SerializeToString,
            ),
            'Meta': grpc.unary_unary_rpc_method_handler(
                    servicer.Meta,
                    request_deserializer=app__pb2.MetaRequest.FromString,
                    response_serializer=app__pb2.MetaResponse.SerializeToString,
            ),
            'ListGenomes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGenomes,
                    request_deserializer=app__pb2.ListGenomesRequest.FromString,
                    response_serializer=app__pb2.ListGenomesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pbuf.BiobtreeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pbuf.BiobtreeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BiobtreeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/Search',
            app__pb2.SearchRequest.SerializeToString,
            app__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/Mapping',
            app__pb2.MappingRequest.SerializeToString,
            app__pb2.MappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Entry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/Entry',
            app__pb2.EntryRequest.SerializeToString,
            app__pb2.EntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Page(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/Page',
            app__pb2.PageRequest.SerializeToString,
            app__pb2.PageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Filter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/Filter',
            app__pb2.FilterRequest.SerializeToString,
            app__pb2.FilterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Meta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/Meta',
            app__pb2.MetaRequest.SerializeToString,
            app__pb2.MetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGenomes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pbuf.BiobtreeService/ListGenomes',
            app__pb2.ListGenomesRequest.SerializeToString,
            app__pb2.ListGenomesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
